apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
  stripe-secret-key: "YOUR_STRIPE_TEST_KEY_HERE"
  stripe-webhook-key: "whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
stringData:
  uri: "mongodb+srv://<db_username>:<db_password>@cluster0.se1pjsu.mongodb.net/?appName=Cluster0"
